BACKUP DICTIONARY

fullDict3 = {
    '0':{
        '0data':'0datttaaa',
        '0mada':'0mmmaadaa'
    },
    'a':{
        'arbre':'tree',
        'arc-en-ciel':'rainbow'
    },
    'b':{
        'bierre':'beer',
        'belle':'beautiful'       
    },
    'c':{
        'chat':'cat',
        'cable':'cable'    
    },
    'd':{   
        'dire':'say',
        'damme':'woman'
    },
    'e':{
        'epicerie':'grocery',
        'equitable':'equitable'            
    },
    'f':{
        'fou':'crazy',
        'four':'oven'    
    },
    'g':{
        'gentil':'nice',
        'gros':'big'    
    },
    'h':{
        'horloge':'clock',
        'horaire':'schedule'    
    },
    'i':{
        'ici':'here',
        'irlandais':'irish'    
    },
    'j':{
        'jour':'day',
        'je':'I'    
    },
    'k':{
        'kerosene':'kerosene',
        'karma':'karma'    
    },
    'l':{
        'lent':'slow',
        'larme':'tear'    
    },
    'm':{
        'molle':'soft',
        'mars':'march'    
    },
    'n':{
        'nord':'north',
        'narcotique':'narcotic'    
    },
    'o':{
        'orignal':'moose',
        'osti':'fuck'    
    },
    'p':{
        'partage':'share',
        'patine':'skate'    
    },
    'q':{
        'qualite':'quality',
        'quand':'when'    
    },
    'r':{
        'regarde':'look',
        'rang':'row'    
    },
    's':{
        'serieux':'serious',
        'serre':'hold'    
    },
    't':{
        'tante':'aunt',
        'tarte':'pie'    
    },
    'u':{
        'univert':'universe',
        'urine':'urine'    
    },
    'v':{
        'valeur':'value',
        'vaste':'wide'    
    },
    'w':{
        'william':'william',
        'walabie':'walaby'    
    },
    'x':{
        'xalas':'xalas',
        'xylophone':'xylophone'    
    },
    'y':{
        'yser':'yser',
        'yser2':'yser2'    
    },
    'z':{
        'zebre':'zebra',
        'zape':'zepa'    
    }
}

fullDict = [
    {
        'rat':'rat',
        'tortue':'turtle',
        'lapin':'rabbit',
        'arbre':'tree',
        'arc-en-ciel':'rainbow',
        'bierre':'beer',
        'belle':'beautiful'
    }
]

fullDict2 = {
    {
        '0data':'0datttaaa',
        '0mada':'0mmmaadaa'
    },
    {
        'arbre':'tree',
        'arc-en-ciel':'rainbow'
    },
    {
        'bierre':'beer',
        'belle':'beautiful'       
    },
    {
        'chat':'cat',
        'cable':'cable'    
    },
    {   
        'dire':'say',
        'damme':'woman'
    },
    {
        'epicerie':'grocery',
        'equitable':'equitable'            
    },
    {
        'fou':'crazy',
        'four':'oven'    
    },
    {
        'gentil':'nice',
        'gros':'big'    
    }
}

dictLetterA = {}

dictLetterB = {}